import pathlib

configfile: "config.yml"

rule all:
  input: 
    config["pdbs"]


rule install_alphafold:
	output:
	shell:
		"wget https://raw.githubusercontent.com/YoshitakaMo/localcolabfold/main/install_colabfold_linux.sh -O resources/ &&"
		"cd resources &&"
		"bash install_colabfold_linux.sh"


rule predict:
  input: fasta="fasta/{name}.fasta", script="resources/colabfold/colabfold-conda/bin/python resources/colabfold/runner_af2advanced.py"
  output: "pdb/{name}"
  shell:
  """
  ./resources/colabfold/colabfold-conda/bin/python resources/colabfold/runner_af2advanced.py -i {input.fasta} -o {output}
  """


